/// Flutter icons WeatherAppIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WeatherAppIcons
///      fonts:
///       - asset: fonts/WeatherAppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WeatherAppIcons {
  WeatherAppIcons._();

  static const _kFontFam = 'WeatherAppIcons';
  static const String _kFontPkg = null;

  static const IconData moisture = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thermometer_sun = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thermometer_half = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
